### ISSUE TITLE
Circular import & closure over self?

### ISSUE THREAD

**Issue by johannahaffner** [patrick-kidger/optimistix#102]
Hi Patrick, 

I'm banging my head at some weirdness and hoping that you have seen that before :D 

Context: I'm writing tests for a new top-level API `quadratic_solve`. For this one, I wrote a `fn_rewrite` that is pretty much copied from the one used in `minimise`. Now, when testing this thing, I get very weird behaviour. It appears to close over itself?

After it is defined, it has nothing in its closure, but immediately after calling `quadratic_solve`, the output of 

```python
jax.debug.print("fn rewrite type: {}", type(_rewrite_quadratic))
jax.debug.print("fn type: {}", type(_rewrite_quadratic))
jax.debug.print("fn_rewrite __code__: {}", _rewrite_quadratic.__code__.co_freevars if hasattr(_rewrite_quadratic, '__code__') else None)
jax.debug.print("fn_rewrite closure: {}", _rewrite_quadratic.__closure__)
if _rewrite_quadratic.__closure__:
        jax.debug.print("contents: {}", [cell.cell_contents for cell in _rewrite_quadratic.__closure__])
```

Is 

```
fn rewrite type: <class 'function'>
fn rewrite structure: PyTreeDef(*)
fn_rewrite __code__: ('fn', 'param_signature', 'wrapped_fn_holder', 'wrapped_fn_impl')
fn_rewrite closure: (<cell at 0x10b882f50: function object at 0x10b887380>, <cell at 0x10b880940: Signature object at 0x10b882410>, <cell at 0x10b881420: list object at 0x10b87cf80>, <cell at 0x10b882590: function object at 0x10b887600>)
contents: [<function _rewrite_quadratic at 0x10b887380>, <Signature (quadratic_minimum, _, inputs) -> Any>, [<weakref at 0x10b8a9940; to 'function' at 0x10b8876a0 (_rewrite_quadratic)>], <function jaxtyped.<locals>.wrapped_fn_impl at 0x10b887600>]
 ```

This is literally the first thing that happens inside `quadratic_solve` now. (I even commented out the `eqx.filter_jit` decorator.)
For now, I have not implemented conversion to `minimise` or `root_find`.

The definition is 

```python
def _rewrite_quadratic(quadratic_minimum, _, inputs):
    quadratic_minimise_fn, _, _, args, *_ = inputs
    del inputs

    def no_aux(x):
        f_val, _ = quadratic_minimise_fn(x, args)
        return f_val

    return jax.grad(no_aux)(quadratic_minimum)
```
If I define that elsewhere (e.g. a notebook, just not in `_quadratic_solve.py`) its closure is empty.

There is probably something simple I'm not seeing. I can try to make an MWE, too!

**Comment by patrick-kidger** [comment]
Hmm from your `co_freevars` it looks like you're inspecting a jaxtyping-wrapped function. In this case then the function you have a hold of:

https://github.com/patrick-kidger/jaxtyping/blob/b2f16e84ee635cec52db2c1b766e533db620c5b7/jaxtyping/_decorator.py#L541

which will close over this internal function:

https://github.com/patrick-kidger/jaxtyping/blob/b2f16e84ee635cec52db2c1b766e533db620c5b7/jaxtyping/_decorator.py#L442

which closes over the original function you defined:

https://github.com/patrick-kidger/jaxtyping/blob/b2f16e84ee635cec52db2c1b766e533db620c5b7/jaxtyping/_decorator.py#L484

Since you're talking about rewrite-fns then I'm guessing this might be in the context of `optx.implicit_jvp`, and that you need the same fix as here:

https://github.com/patrick-kidger/optimistix/blob/396aac6fa66f6b6f1b6e3d3538cb77003362979a/optimistix/_minimise.py#L33-L35

**Comment by johannahaffner** [comment]
Yes, that was it! Thanks <3
