### ISSUE TITLE
AssertionError: assert _is_global_function(fn_primal)

### ISSUE THREAD

**Issue by GaetanLepage** [patrick-kidger/optimistix#79]
Context: packaging `bayeux-ml` on nixpkgs.

While running the test suite for `optimistix` (v0.0.7), most (347) tests fail with:
```
>       assert _is_global_function(fn_primal)
E       AssertionError
E       --------------------
E       For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
```

Could it be caused by the jax version used (0.4.28) ?

Thanks in advance for your help.

**Comment by patrick-kidger** [comment]
Ah, this was a jaxtyping-optimistix version mismatch. It was fixed in https://github.com/patrick-kidger/optimistix/commit/fb63b4cd03648cdafda3e87fecb5c11be3d10b0e, I just haven't done a new Optimistix release since then.
Would it be useful to you to have a release? I'm planning on doing one soon anyway to fix some JAX deprecation warnings.

**Comment by GaetanLepage** [comment]
Ok thanks for the quick answer !
It is not urgent, if it's a matter of <20 days it should be fine. Otherwise I will always be able to fetch the patch.

**Comment by GaetanLepage** [comment]
Hi !
Do you have a better idea of when the next release could happen ?

**Comment by GaetanLepage** [comment]
Thank you very much :)
