### ISSUE TITLE
Bounded Dogleg

### ISSUE THREAD

**Issue by djbower** [patrick-kidger/optimistix#97]
I'm interested making a bounded Dogleg solver by wrapping the existing Dogleg, such that it supports the `lower` and `upper` arguments to maintain consistency with the interface for the `Newton` solver. Could you provide a couple of pointers on how to implement this, and whether you prefer I implement it into Optimistix directly or just my own code for the time being?

**Comment by patrick-kidger** [comment]
I think for this I'll defer to @johannahaffner who has been thinking about bounded solvers recently :)

**Comment by johannahaffner** [comment]
Hi Dan, 

I actually already implemented this for the Gauss-Newton solvers - bounds may be passed as options and `y` is then clipped to these. I've been using this for chemical reaction networks, to clip the search space to a region in which the objective is convex. I can rebase, throw in a test for the tree-clipping and push this to my own fork of optimistix, then you can use it right away. 
(@patrick-kidger this could be a PR, but since the interface might change soon I would not opt for that.)

We're indeed working on constrained optimisation in optimistix, and this will include constrained trust-region solvers too, although I didn't get to that part yet (planning to change that in the next two weeks).

**Comment by johannahaffner** [comment]
You can try https://github.com/johannahaffner/optimistix/tree/gauss-newton-clip. 

For now I'm not checking that the first guess `y0` is inside the bounded region, but since every step is clipped all others should be.

**Comment by djbower** [comment]
This is fantastic, thanks for sharing!
